<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <artifactId>moonbox-agent</artifactId>
        <groupId>com.vivo.internet</groupId>
        <version>1.0.0-SNAPSHOT</version>
    </parent>

    <modelVersion>4.0.0</modelVersion>

    <artifactId>moonbox-java-agent</artifactId>
    <version>1.0.0-SNAPSHOT</version>
    <packaging>pom</packaging>

    <properties>
        <lombok.version>1.18.30</lombok.version>
        <sandbox.api.version>1.4.0</sandbox.api.version>
<!--        <org.slf4j.version>1.7.24</org.slf4j.version>-->
<!--        <logback.version>1.2.1</logback.version>-->
<!--        <ttl.version>2.10.2</ttl.version>-->
<!--        <fastjson.version>1.2.83</fastjson.version>-->
<!--        <commons-lang3.version>3.6</commons-lang3.version>-->
<!--        <commons-csv.version>1.7</commons-csv.version>-->
        <!-- SLF4J (日志门面) -->
        <org.slf4j.version>2.0.7</org.slf4j.version>

        <!-- Logback (日志实现) -->
        <logback.version>1.4.7</logback.version>

        <!-- TransmittableThreadLocal (阿里线程上下文传递) -->
        <ttl.version>2.14.0</ttl.version>

        <!-- Fastjson (阿里JSON库) -->
        <fastjson.version>2.0.34</fastjson.version>

        <!-- Apache Commons Lang3 -->
        <commons-lang3.version>3.12.0</commons-lang3.version>
        <org.ow2.asm.version>9.8</org.ow2.asm.version>

        <!-- Apache Commons CSV -->
        <commons-csv.version>1.10.0</commons-csv.version>
        <maven.compiler.source>${java.version}</maven.compiler.source>
        <maven.compiler.target>${java.version}</maven.compiler.target>
        <metainf-services.version>1.11</metainf-services.version>
    </properties>

    <modules>
        <module>moonbox-module</module>
        <module>moonbox-plugins</module>
        <module>moonbox-api</module>
        <module>moonbox-core</module>
    </modules>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>org.kohsuke.metainf-services</groupId>
                <artifactId>metainf-services</artifactId>
                <version>${metainf-services.version}</version>
                <scope>compile</scope>
            </dependency>

            <dependency>
                <groupId>com.alibaba.jvm.sandbox</groupId>
                <artifactId>sandbox-api</artifactId>
                <version>${sandbox.api.version}</version>
            </dependency>

            <dependency>
                <groupId>org.slf4j</groupId>
                <artifactId>slf4j-api</artifactId>
                <version>${org.slf4j.version}</version>
            </dependency>

            <dependency>
                <groupId>ch.qos.logback</groupId>
                <artifactId>logback-classic</artifactId>
                <version>${logback.version}</version>
            </dependency>

            <dependency>
                <groupId>com.alibaba</groupId>
                <artifactId>transmittable-thread-local</artifactId>
                <version>${ttl.version}</version>
            </dependency>

            <dependency>
                <groupId>com.alibaba</groupId>
                <artifactId>fastjson</artifactId>
                <version>${fastjson.version}</version>
            </dependency>

            <dependency>
                <groupId>org.apache.commons</groupId>
                <artifactId>commons-lang3</artifactId>
                <version>${commons-lang3.version}</version>
            </dependency>
            <dependency>
                <groupId>org.apache.commons</groupId>
                <artifactId>commons-csv</artifactId>
                <version>${commons-csv.version}</version>
            </dependency>
            <dependency>
                <groupId>com.esotericsoftware</groupId>
                <artifactId>kryo</artifactId>
                <version>5.3.0</version>
            </dependency>
            <dependency>
                <groupId>com.vivo.internet</groupId>
                <artifactId>moonbox-common</artifactId>
                <version>1.0.0-SNAPSHOT</version>
            </dependency>

<!--            <dependency>-->
<!--                <groupId>com.vivo.internet</groupId>-->
<!--                <artifactId>moonbox-hessian-lite</artifactId>-->
<!--                <version>1.0.0-SNAPSHOT</version>-->
<!--            </dependency>-->

            <dependency>
                <groupId>com.vivo.internet</groupId>
                <artifactId>moonbox-data</artifactId>
                <version>1.0.0-SNAPSHOT</version>
            </dependency>

            <dependency>
                <groupId>org.ow2.asm</groupId>
                <artifactId>asm</artifactId>
                <version>${org.ow2.asm.version}</version>
            </dependency>
            <dependency>
                <groupId>org.ow2.asm</groupId>
                <artifactId>asm-commons</artifactId>
                <version>${org.ow2.asm.version}</version>
            </dependency>
            <dependency>
                <groupId>org.ow2.asm</groupId>
                <artifactId>asm-util</artifactId>
                <version>${org.ow2.asm.version}</version>
            </dependency>

        </dependencies>
    </dependencyManagement>
    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>${maven.compiler.plugin.version}</version>
                <configuration>
                    <source>${java.version}</source>
                    <target>${java.version}</target>
                    <encoding>UTF-8</encoding>
                    <compilerArgs>
                        <arg>--add-opens=jdk.compiler/com.sun.tools.javac.processing=ALL-UNNAMED</arg>
                        <arg>--add-opens=jdk.compiler/com.sun.tools.javac.util=ALL-UNNAMED</arg>
                    </compilerArgs>
                </configuration>
            </plugin>
        </plugins>

    </build>
</project>